### ISSUE TITLE
Stack failed on CodeBuildLogs

### ISSUE THREAD

**Issue by rsignell-usgs** [zflamig/dask-era5#3]
Resource of type 'AWS::Logs::LogGroup' with identifier '{"/properties/LogGroupName":"/aws/codebuild/era5"}' already exists.

![2020-11-16_9-26-19](https://user-images.githubusercontent.com/1872600/99264109-0e447800-27ee-11eb-9b2a-9b41aa5b15d7.png)

**Comment by zflamig** [comment]
This was fixed in https://github.com/zflamig/dask-era5/commit/f1950d96e28cab7cbf1825a067744c7dc4309e4a but you may need to manually delete it since you had a previous version

**Comment by rsignell-usgs** [comment]
@zflamig, okay, what do I delete?

**Comment by rsignell-usgs** [comment]
Oh, delete the CloudFormation stack called `era5`? 
Trying that...
... nope, that didn't work.

**Comment by rsignell-usgs** [comment]
Ah, the `era5` [CloudWatch log-group](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups):

![2020-11-17_11-30-02](https://user-images.githubusercontent.com/1872600/99417772-4a4c0b80-28c8-11eb-90e2-e566604485ec.png)

**Comment by rsignell-usgs** [comment]
That worked!
